### ISSUE TITLE
歌词抄录・冀西南林路行 | TC Bebop

### ISSUE THREAD

**Issue by toshiko0o** [toshiko0o/toshiko0o.github.io#3]
https://toshiko0o.github.io/2020/12/22/%E6%AD%8C%E8%AF%8D%E6%8A%84%E5%BD%95%E3%83%BB%E5%86%80%E8%A5%BF%E5%8D%97%E6%9E%97%E8%B7%AF%E8%A1%8C/ 

 早
 器乐曲
 泥河
 骤雨重山 将甘苦注入他
 气息交换 吞石铁吐泥沙
 水鸟风帆 跟随着他舒展
 知觉情感 在形成严格而缓慢
 可听到雷声隐隐
 可感到夏日来临
 高地奔流 掠山光过太行
 平原午休 纵鱼儿跃夕阳
 明日壮阔 就奋力托帆船
 明日难测 就放任潮流划水道
 可听到雷声隐隐
 可感到未知来临
 不速之客 一贫如洗
 劳动 饮酒 叹息
 夜宿河床枕露珠
 测量绘图 爆破合围
 加固文

**Comment by frankensoul** [comment]
呐，为啥评论还要github账号登录的啊？

**Comment by frankensoul** [comment]
人间明暗

**Comment by toshiko0o** [comment]
> @frankensoul
> 呐，为啥评论还要github账号登录的啊？

因为我用的这个gitalk其实是用github的issues来实现评论功能的（而且github账号应该人人都有的吧，有的吧有的吧
